name: "AI PR Automation"
description: "Runs AI code assistants (Claude Code or Codex) to create automated PRs based on merged PRs"
inputs:
  provider:
    description: "AI provider to use: 'claude' or 'codex'"
    required: false
    default: "claude"
  prompt_template:
    description: "Prompt template with variable placeholders ({{PR_DIFF}}, {{PR_TITLE}}, etc.)"
    required: true
  pr_number:
    description: "PR number to process. If not provided, will be extracted from the GitHub event context."
    required: false
  # Claude-specific inputs
  anthropic_api_key:
    description: "Anthropic API key for Claude Code"
    required: false
  claude_code_oauth_token:
    description: "Claude Code OAuth token (alternative to anthropic_api_key)"
    required: false
  use_bedrock:
    description: "Use Amazon Bedrock instead of direct Anthropic API"
    required: false
    default: "false"
  use_vertex:
    description: "Use Google Vertex AI instead of direct Anthropic API"
    required: false
    default: "false"
  use_foundry:
    description: "Use Microsoft Foundry instead of direct Anthropic API"
    required: false
    default: "false"
  claude_args:
    description: "Additional arguments to pass to Claude Code CLI"
    required: false
    default: ""
  # Codex-specific inputs
  openai_api_key:
    description: "OpenAI API key for Codex"
    required: false
  responses_api_endpoint:
    description: "Optional Responses API endpoint override for Codex"
    required: false
  codex_args:
    description: "Extra arguments forwarded to codex exec"
    required: false
    default: ""
  codex_sandbox:
    description: "Sandbox mode for Codex: workspace-write, read-only, or danger-full-access"
    required: false
    default: "workspace-write"
  codex_safety_strategy:
    description: "Safety strategy for Codex: drop-sudo, unprivileged-user, read-only, or unsafe"
    required: false
    default: "drop-sudo"
  # Common inputs
  branch_prefix:
    description: "Prefix for generated branches"
    required: false
    default: "ai/"
  pr_title_template:
    description: "Template for created PR title (supports variable placeholders)"
    required: false
    default: "chore: Automated changes from PR #{{PR_NUMBER}}"
  pr_body_template:
    description: "Template for created PR body (supports variable placeholders)"
    required: false
    default: "This PR contains automated changes generated by AI based on merged PR #{{PR_NUMBER}}."
  base_branch:
    description: "Base branch to create new branch from (defaults to repository default branch)"
    required: false
  github_token:
    description: "GitHub API token (pass ${{ secrets.GITHUB_TOKEN }} from your workflow)"
    required: true
outputs:
  branch_name:
    description: "Name of the branch created by the AI assistant"
    value: ${{ steps.delegate.outputs.branch_name }}
  has_changes:
    description: "Whether the AI assistant made any changes"
    value: ${{ steps.delegate.outputs.has_changes }}
runs:
  using: "composite"
  steps:
    - name: Run AI automation
      id: delegate
      uses: ./.github/actions/ai-automation
      with:
        provider: ${{ inputs.provider }}
        prompt_template: ${{ inputs.prompt_template }}
        pr_number: ${{ inputs.pr_number }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        use_bedrock: ${{ inputs.use_bedrock }}
        use_vertex: ${{ inputs.use_vertex }}
        use_foundry: ${{ inputs.use_foundry }}
        claude_args: ${{ inputs.claude_args }}
        openai_api_key: ${{ inputs.openai_api_key }}
        responses_api_endpoint: ${{ inputs.responses_api_endpoint }}
        codex_args: ${{ inputs.codex_args }}
        codex_sandbox: ${{ inputs.codex_sandbox }}
        codex_safety_strategy: ${{ inputs.codex_safety_strategy }}
        branch_prefix: ${{ inputs.branch_prefix }}
        pr_title_template: ${{ inputs.pr_title_template }}
        pr_body_template: ${{ inputs.pr_body_template }}
        base_branch: ${{ inputs.base_branch }}
        github_token: ${{ inputs.github_token }}

