#!/usr/bin/env bun

/**
 * Creates a pull request after AI code assistant has made changes.
 */

import * as core from "@actions/core";
import { Octokit } from "@octokit/rest";

/**
 * Substitutes variables in a template string
 */
function substituteVariables(template: string, variables: Record<string, string>): string {
  let result = template;
  for (const [key, value] of Object.entries(variables)) {
    const regex = new RegExp(`\\{\\{${key}\\}\\}`, "g");
    result = result.replace(regex, value);
  }
  return result;
}

/**
 * Checks if there are any changes between two branches using GitHub API
 */
async function hasChanges(
  octokit: Octokit,
  owner: string,
  repo: string,
  baseBranch: string,
  branchName: string,
): Promise<boolean> {
  try {
    const { data } = await octokit.rest.repos.compareCommitsWithBasehead({
      owner,
      repo,
      basehead: `${baseBranch}...${branchName}`,
    });

    return (data.total_commits ?? 0) > 0 || (data.files?.length ?? 0) > 0;
  } catch (error) {
    // If comparison fails, assume there are changes to be safe
    console.warn(`Failed to compare branches: ${error instanceof Error ? error.message : String(error)}`);
    return true;
  }
}

async function main() {
  try {
    const branchName = process.env.BRANCH_NAME;
    if (!branchName) {
      console.log("No branch name provided, skipping PR creation");
      return;
    }

    const githubToken = process.env.GITHUB_TOKEN;
    if (!githubToken) {
      throw new Error("GITHUB_TOKEN environment variable is required");
    }

    const repository = process.env.REPOSITORY || "";
    if (!repository) {
      throw new Error("REPOSITORY environment variable is required");
    }

    const [owner, repo] = repository.split("/");
    if (!owner || !repo) {
      throw new Error(`Invalid REPOSITORY format: ${repository}. Expected 'owner/repo'`);
    }

    const baseBranch = process.env.BASE_BRANCH || "main";
    const prTitleTemplate = process.env.PR_TITLE_TEMPLATE || "chore: Automated changes";
    const prBodyTemplate =
      process.env.PR_BODY_TEMPLATE ||
      "This PR contains automated changes generated by AI.\n\nGenerated with [docspec-ai/github-ai-actions](https://github.com/docspec-ai/github-ai-actions)";

    // Get PR metadata for variable substitution
    const prNumber = process.env.PR_NUMBER || "";
    const prTitle = process.env.PR_TITLE || "";
    const prAuthor = process.env.PR_AUTHOR || "";
    const prBody = process.env.PR_BODY || "";

    // Create Octokit client
    const apiUrl = process.env.GITHUB_API_URL || "https://api.github.com";
    const octokit = new Octokit({
      auth: githubToken,
      baseUrl: apiUrl,
    });

    // Check if there are any changes
    if (!(await hasChanges(octokit, owner, repo, baseBranch, branchName))) {
      console.log("No changes detected, skipping PR creation");
      return;
    }

    // Substitute variables in title and body
    const variables: Record<string, string> = {
      PR_NUMBER: prNumber,
      PR_TITLE: prTitle,
      PR_AUTHOR: prAuthor,
      PR_BODY: prBody,
      REPOSITORY: repository,
      BASE_BRANCH: baseBranch,
    };

    const finalTitle = substituteVariables(prTitleTemplate, variables);
    const finalBody = substituteVariables(prBodyTemplate, variables);

    // Check if PR already exists for this branch
    try {
      const { data: existingPRs } = await octokit.rest.pulls.list({
        owner,
        repo,
        head: `${owner}:${branchName}`,
        base: baseBranch,
        state: "open",
      });

      if (existingPRs.length > 0 && existingPRs[0]) {
        const existingPR = existingPRs[0];
        console.log(`PR already exists: ${existingPR.html_url}`);
        core.setOutput("pr_url", existingPR.html_url);
        return;
      }
    } catch (error) {
      console.warn(`Failed to check for existing PRs: ${error instanceof Error ? error.message : String(error)}`);
      // Continue to try creating a new PR
    }

    // Create PR using GitHub API
    console.log(`Creating PR from ${branchName} to ${baseBranch}`);
    console.log(`Title: ${finalTitle}`);

    try {
      const { data: pr } = await octokit.rest.pulls.create({
        owner,
        repo,
        title: finalTitle,
        body: finalBody,
        head: branchName,
        base: baseBranch,
      });

      console.log(`PR created successfully: ${pr.html_url}`);
      core.setOutput("pr_url", pr.html_url);
      core.setOutput("pr_number", String(pr.number));
    } catch (error) {
      // Check if error is because PR already exists (shouldn't happen after our check, but handle it anyway)
      if (error instanceof Error && error.message.includes("already exists")) {
        console.log("PR already exists (detected during creation)");
        // Try to find the existing PR
        try {
          const { data: existingPRs } = await octokit.rest.pulls.list({
            owner,
            repo,
            head: `${owner}:${branchName}`,
            base: baseBranch,
            state: "all",
          });

          if (existingPRs.length > 0 && existingPRs[0]) {
            const existingPR = existingPRs[0];
            console.log(`Existing PR: ${existingPR.html_url}`);
            core.setOutput("pr_url", existingPR.html_url);
            core.setOutput("pr_number", String(existingPR.number));
          }
        } catch (findError) {
          console.warn("Could not retrieve existing PR:", findError);
        }
      } else {
        throw error;
      }
    }
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : String(error);
    core.setFailed(`Failed to create PR: ${errorMessage}`);
    process.exit(1);
  }
}

if (import.meta.main) {
  main();
}

