name: AI Automation on Comment

on:
  issue_comment:
    types: [created]

jobs:
  ai-automation:
    # Only run on PR comments (not regular issues)
    # You can customize this condition based on your needs
    if: |
      github.event.issue.pull_request != null &&
      contains(github.event.comment.body, '/ai-process')
    runs-on: ubuntu-latest
    steps:
      - name: Run AI automation
        uses: docspec-ai/github-ai-actions@main
        with:
          provider: claude
          prompt_template: |
            A comment was made on PR #{{PR_NUMBER}}:

            PR: {{PR_TITLE}}
            Author: {{PR_AUTHOR}}

            Changes in this PR:
            {{PR_DIFF}}

            Please review the changes and update documentation as needed.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          pr_title_template: "docs: Auto-update for PR #{{PR_NUMBER}}"
