name: AI Automation on Comment

on:
  issue_comment:
    types: [created]

jobs:
  ai-automation:
    # Only run on PR comments (not regular issues)
    # You can customize this condition based on your needs
    if: |
      github.event.issue.pull_request != null &&
      contains(github.event.comment.body, '/ai-process')
    uses: docspec-ai/github-ai-actions/.github/workflows/pr-automation.yml@main
    with:
      provider: claude
      workflow_repository: docspec-ai/github-ai-actions
      prompt_template: |
        A comment was made on PR #{{PR_NUMBER}}:
        
        PR: {{PR_TITLE}}
        Author: {{PR_AUTHOR}}
        
        Changes in this PR:
        {{PR_DIFF}}
        
        Please review the changes and update documentation as needed.
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
      pr_title_template: "docs: Auto-update for PR #{{PR_NUMBER}}"
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

