name: PR AI Automation with Codex

on:
  pull_request:
    types: [closed]

jobs:
  post-merge:
    # Only run when PR is actually merged (not just closed)
    if: github.event.pull_request.merged == true
    uses: docspec-ai/github-ai-actions/.github/workflows/pr-automation.yml@main
    with:
      # Required: Specify the workflow repository (where the scripts are)
      workflow_repository: docspec-ai/github-ai-actions
      workflow_ref: main
      
      # Select Codex as the provider
      provider: codex
      
      # Your custom prompt with variable placeholders
      prompt_template: |
        Analyze the changes in this merged PR:
        
        PR #{{PR_NUMBER}}: {{PR_TITLE}}
        Author: {{PR_AUTHOR}}
        
        Full diff:
        {{PR_DIFF}}
        
        Changed files:
        {{CHANGED_FILES}}
        
        Based on these changes, please:
        1. Update CHANGELOG.md to document what was added
        2. Ensure all new public APIs are documented
        3. Check for any breaking changes and note them
        
        Repository: {{REPOSITORY}}
        Base branch: {{BASE_BRANCH}}
      
      # Codex authentication
      openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      
      # Optional: Codex configuration
      codex_sandbox: workspace-write
      codex_safety_strategy: drop-sudo
      codex_args: '["--max-turns", "5"]'
      
      # Optional: For Azure OpenAI
      # responses_api_endpoint: "https://YOUR_PROJECT_NAME.openai.azure.com/openai/v1/responses"
      
      # Optional: Customize branch naming
      branch_prefix: "ai/"
      
      # Optional: Customize PR title and body
      pr_title_template: "docs: Update CHANGELOG for PR #{{PR_NUMBER}}"
      pr_body_template: |
        This PR contains automated documentation updates generated by AI.
        
        **Original PR**: #{{PR_NUMBER}} - {{PR_TITLE}}
        **Author**: @{{PR_AUTHOR}}
        
        Generated with [Codex](https://github.com/openai/codex)
      
      # Optional: Specify base branch (defaults to repository default)
      base_branch: "main"
    secrets:
      # Pass secrets if not using input parameters
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

