name: PR AI Automation

on:
  pull_request:
    types: [closed]

jobs:
  post-merge:
    # Only run when PR is actually merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Run AI automation
        uses: docspec-ai/github-ai-actions@main
        with:
          # Select AI provider: 'claude' (default) or 'codex'
          provider: claude

          # Your custom prompt with variable placeholders
          prompt_template: |
            Analyze the changes in this merged PR:

            PR #{{PR_NUMBER}}: {{PR_TITLE}}
            Author: {{PR_AUTHOR}}

            Full diff:
            {{PR_DIFF}}

            Changed files:
            {{CHANGED_FILES}}

            Based on these changes, please:
            1. Update CHANGELOG.md to document what was added
            2. Ensure all new public APIs are documented
            3. Check for any breaking changes and note them

            Repository: {{REPOSITORY}}
            Base branch: {{BASE_BRANCH}}

          # Claude authentication (choose one)
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # OR
          # claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # OR for cloud providers:
          # use_bedrock: true
          # use_vertex: true
          # use_foundry: true

          # Optional: Customize branch naming
          branch_prefix: "ai/"

          # Optional: Customize PR title and body
          pr_title_template: "docs: Update CHANGELOG for PR #{{PR_NUMBER}}"
          pr_body_template: |
            This PR contains automated documentation updates generated by AI.

            **Original PR**: #{{PR_NUMBER}} - {{PR_TITLE}}
            **Author**: @{{PR_AUTHOR}}

            Generated with [Claude Code](https://claude.ai/code)

          # Optional: Additional Claude Code arguments
          claude_args: "--max-turns 10"

          # Optional: Specify base branch (defaults to repository default)
          base_branch: "main"
