name: "AI PR Automation"
description: "Runs AI code assistants (Claude Code or Codex) to create automated PRs based on merged PRs"
inputs:
  provider:
    description: "AI provider to use: 'claude' or 'codex'"
    required: false
    default: "claude"
  prompt_template:
    description: "Prompt template with variable placeholders ({{PR_DIFF}}, {{PR_TITLE}}, etc.)"
    required: true
  pr_number:
    description: "PR number to process. If not provided, will be extracted from the GitHub event context."
    required: false
  # Claude-specific inputs
  anthropic_api_key:
    description: "Anthropic API key for Claude Code"
    required: false
  claude_code_oauth_token:
    description: "Claude Code OAuth token (alternative to anthropic_api_key)"
    required: false
  use_bedrock:
    description: "Use Amazon Bedrock instead of direct Anthropic API"
    required: false
    default: "false"
  use_vertex:
    description: "Use Google Vertex AI instead of direct Anthropic API"
    required: false
    default: "false"
  use_foundry:
    description: "Use Microsoft Foundry instead of direct Anthropic API"
    required: false
    default: "false"
  claude_args:
    description: "Additional arguments to pass to Claude Code CLI"
    required: false
    default: ""
  # Codex-specific inputs
  openai_api_key:
    description: "OpenAI API key for Codex"
    required: false
  responses_api_endpoint:
    description: "Optional Responses API endpoint override for Codex"
    required: false
  codex_args:
    description: "Extra arguments forwarded to codex exec"
    required: false
    default: ""
  codex_sandbox:
    description: "Sandbox mode for Codex: workspace-write, read-only, or danger-full-access"
    required: false
    default: "workspace-write"
  codex_safety_strategy:
    description: "Safety strategy for Codex: drop-sudo, unprivileged-user, read-only, or unsafe"
    required: false
    default: "drop-sudo"
  # Common inputs
  branch_prefix:
    description: "Prefix for generated branches"
    required: false
    default: "ai/"
  pr_title_template:
    description: "Template for created PR title (supports variable placeholders)"
    required: false
    default: "chore: Automated changes from PR #{{PR_NUMBER}}"
  pr_body_template:
    description: "Template for created PR body (supports variable placeholders)"
    required: false
    default: "This PR contains automated changes generated by AI based on merged PR #{{PR_NUMBER}}."
  base_branch:
    description: "Base branch to create new branch from (defaults to repository default branch)"
    required: false
  github_token:
    description: "GitHub API token (pass ${{ secrets.GITHUB_TOKEN }})"
    required: true
  # Plan phase inputs
  enable_plan:
    description: "Enable plan phase before implementation (runs LLM twice: once for planning, once for implementation)"
    required: false
    default: "false"
  plan_prompt_template:
    description: "Optional prompt template for the plan phase. If not provided, uses a default plan prompt."
    required: false
  plan_model:
    description: "Optional model to use for plan phase (overrides default model)"
    required: false
outputs:
  branch_name:
    description: "Name of the branch created by the AI assistant"
    value: ${{ steps.ai-execution.outputs.branch_name }}
  has_changes:
    description: "Whether the AI assistant made any changes"
    value: ${{ steps.ai-execution.outputs.has_changes }}
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun install

    - name: Install Claude Code CLI
      if: inputs.provider == 'claude'
      shell: bash
      run: npm install -g @anthropic-ai/claude-code

    - name: Install Codex CLI
      if: inputs.provider == 'codex' && inputs.enable_plan == 'true'
      shell: bash
      run: npm install -g @openai/codex

    - name: Extract PR number from event
      id: extract-pr-number
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/extract-pr-number.ts
      env:
        PR_NUMBER: ${{ inputs.pr_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
        GITHUB_API_URL: ${{ github.api_url }}

    - name: Prepare plan prompt with PR data
      id: prepare-plan-prompt
      if: inputs.enable_plan == 'true'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/prepare-prompt.ts
      env:
        PROMPT_TEMPLATE: ${{ inputs.plan_prompt_template || 'Create a detailed plan for implementing the changes described in PR #{{PR_NUMBER}}: {{PR_TITLE}}

PR Description:
{{PR_BODY}}

Changed Files:
{{CHANGED_FILES}}

Analyze the requirements and break down the work into clear, actionable steps. Consider the code changes needed, potential edge cases, and testing requirements.' }}
        PR_NUMBER: ${{ steps.extract-pr-number.outputs.pr_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPOSITORY: ${{ github.repository }}
        BASE_BRANCH: ${{ inputs.base_branch || '' }}

    - name: Run plan phase
      id: plan-phase
      if: inputs.enable_plan == 'true'
      shell: bash
      run: cd ${{ github.action_path }} && bun run scripts/run-llm.ts
      env:
        PROVIDER: ${{ inputs.provider }}
        PROMPT: ${{ steps.prepare-plan-prompt.outputs.final_prompt }}
        PERMISSION_MODE: ""
        CAPTURE_OUTPUT: "true"
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        CLAUDE_CODE_OAUTH_TOKEN: ${{ inputs.claude_code_oauth_token }}
        USE_BEDROCK: ${{ inputs.use_bedrock }}
        USE_VERTEX: ${{ inputs.use_vertex }}
        USE_FOUNDRY: ${{ inputs.use_foundry }}
        CLAUDE_ARGS: ${{ inputs.claude_args }}
        MODEL: ${{ inputs.plan_model }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        RESPONSES_API_ENDPOINT: ${{ inputs.responses_api_endpoint }}
        CODEX_ARGS: ${{ inputs.codex_args }}
        CODEX_SANDBOX: "read-only"
        CODEX_SAFETY_STRATEGY: "read-only"

    - name: Prepare prompt with PR data
      id: prepare-prompt
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/prepare-prompt.ts
      env:
        PROMPT_TEMPLATE: ${{ inputs.prompt_template }}
        PR_NUMBER: ${{ steps.extract-pr-number.outputs.pr_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPOSITORY: ${{ github.repository }}
        BASE_BRANCH: ${{ inputs.base_branch || '' }}
        PLAN: ${{ steps.plan-phase.outputs.output }}

    # Create branch for AI execution
    - name: Create branch
      id: create-branch
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/create-branch.ts
      env:
        BASE_BRANCH: ${{ steps.prepare-prompt.outputs.base_branch }}
        BRANCH_PREFIX: ${{ inputs.branch_prefix }}
        PR_NUMBER: ${{ steps.prepare-prompt.outputs.pr_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}

    # Claude Code execution using shared script
    - name: Run Claude Code
      id: claude-code
      if: inputs.provider == 'claude'
      shell: bash
      run: cd ${{ github.action_path }} && bun run scripts/run-llm.ts
      env:
        PROVIDER: "claude"
        PROMPT: ${{ steps.prepare-prompt.outputs.final_prompt }}
        PERMISSION_MODE: "acceptEdits"
        CAPTURE_OUTPUT: "false"
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        CLAUDE_CODE_OAUTH_TOKEN: ${{ inputs.claude_code_oauth_token }}
        USE_BEDROCK: ${{ inputs.use_bedrock }}
        USE_VERTEX: ${{ inputs.use_vertex }}
        USE_FOUNDRY: ${{ inputs.use_foundry }}
        CLAUDE_ARGS: ${{ inputs.claude_args }}

    - name: Commit and push changes
      id: commit-push-claude
      if: inputs.provider == 'claude'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/commit-and-push.ts
      env:
        BRANCH_NAME: ${{ steps.create-branch.outputs.branch_name }}
        PR_NUMBER: ${{ steps.prepare-prompt.outputs.pr_number }}
        PROVIDER: "claude"

    # Codex execution
    - name: Run Codex
      id: codex-exec
      if: inputs.provider == 'codex'
      uses: openai/codex-action@v1
      with:
        openai-api-key: ${{ inputs.openai_api_key }}
        responses-api-endpoint: ${{ inputs.responses_api_endpoint }}
        prompt: ${{ steps.prepare-prompt.outputs.final_prompt }}
        sandbox: ${{ inputs.codex_sandbox }}
        safety-strategy: ${{ inputs.codex_safety_strategy }}
        codex-args: ${{ inputs.codex_args }}

    - name: Commit and push changes
      id: commit-push-codex
      if: inputs.provider == 'codex'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/commit-and-push.ts
      env:
        BRANCH_NAME: ${{ steps.create-branch.outputs.branch_name }}
        PR_NUMBER: ${{ steps.prepare-prompt.outputs.pr_number }}
        PROVIDER: "codex"

    # Set unified outputs
    - name: Set AI execution outputs
      id: ai-execution
      shell: bash
      run: |
        # Check Claude outputs if provider is claude
        if [ "${{ inputs.provider }}" == "claude" ] && [ "${{ steps.commit-push-claude.outputs.has_changes }}" == "true" ]; then
          echo "branch_name=${{ steps.commit-push-claude.outputs.branch_name }}" >> $GITHUB_OUTPUT
          echo "has_changes=true" >> $GITHUB_OUTPUT
        # Check Codex outputs if provider is codex
        elif [ "${{ inputs.provider }}" == "codex" ] && [ "${{ steps.commit-push-codex.outputs.has_changes }}" == "true" ]; then
          echo "branch_name=${{ steps.commit-push-codex.outputs.branch_name }}" >> $GITHUB_OUTPUT
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Create PR if changes exist
      if: steps.ai-execution.outputs.has_changes == 'true'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/create-pr.ts
      env:
        BRANCH_NAME: ${{ steps.ai-execution.outputs.branch_name }}
        BASE_BRANCH: ${{ steps.prepare-prompt.outputs.base_branch }}
        PR_TITLE_TEMPLATE: ${{ inputs.pr_title_template }}
        PR_BODY_TEMPLATE: ${{ inputs.pr_body_template }}
        PR_NUMBER: ${{ steps.prepare-prompt.outputs.pr_number }}
        PR_TITLE: ${{ steps.prepare-prompt.outputs.pr_title }}
        PR_AUTHOR: ${{ steps.prepare-prompt.outputs.pr_author }}
        PR_BODY: ${{ steps.prepare-prompt.outputs.pr_body }}
        REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
