name: "AI PR Automation"
description: "Runs AI code assistants (Claude Code or Codex) to create automated PRs based on merged PRs"
inputs:
  provider:
    description: "AI provider to use: 'claude' or 'codex'"
    required: false
    default: "claude"
  prompt_template:
    description: "Prompt template with variable placeholders ({{PR_DIFF}}, {{PR_TITLE}}, etc.)"
    required: true
  pr_number:
    description: "PR number to process. If not provided, will be extracted from the GitHub event context."
    required: false
  # Claude-specific inputs (matching anthropics/claude-code-action@v1)
  anthropic_api_key:
    description: "Anthropic API key (required for direct Anthropic API)"
    required: false
    default: ""
  claude_code_oauth_token:
    description: "Claude Code OAuth token (alternative to anthropic_api_key)"
    required: false
    default: ""
  use_bedrock:
    description: "Use Amazon Bedrock with OIDC authentication instead of direct Anthropic API"
    required: false
    default: "false"
  use_vertex:
    description: "Use Google Vertex AI with OIDC authentication instead of direct Anthropic API"
    required: false
    default: "false"
  use_foundry:
    description: "Use Microsoft Foundry with OIDC authentication instead of direct Anthropic API"
    required: false
    default: "false"
  claude_args:
    description: "Additional arguments to pass directly to Claude CLI (e.g., '--max-turns 3 --mcp-config /path/to/config.json')"
    required: false
    default: ""
  settings:
    description: "Claude Code settings as JSON string or path to settings JSON file"
    required: false
    default: ""
  use_node_cache:
    description: "Whether to use Node.js dependency caching (set to true only for Node.js projects with lock files)"
    required: false
    default: "false"
  path_to_claude_code_executable:
    description: "Optional path to a custom Claude Code executable. If provided, skips automatic installation and uses this executable instead."
    required: false
    default: ""
  path_to_bun_executable:
    description: "Optional path to a custom Bun executable. If provided, skips automatic Bun installation and uses this executable instead."
    required: false
    default: ""
  show_full_output:
    description: "Show full JSON output from Claude Code. WARNING: This outputs ALL Claude messages including tool execution results which may contain secrets, API keys, or other sensitive information."
    required: false
    default: "false"
  plugins:
    description: "Newline-separated list of Claude Code plugin names to install (e.g., 'code-review@claude-code-plugins\nfeature-dev@claude-code-plugins')"
    required: false
    default: ""
  plugin_marketplaces:
    description: "Newline-separated list of Claude Code plugin marketplace Git URLs to install from"
    required: false
    default: ""
  # Codex-specific inputs
  openai_api_key:
    description: "OpenAI API key for Codex"
    required: false
  responses_api_endpoint:
    description: "Optional Responses API endpoint override for Codex"
    required: false
  codex_args:
    description: "Extra arguments forwarded to codex exec"
    required: false
    default: ""
  codex_sandbox:
    description: "Sandbox mode for Codex: workspace-write, read-only, or danger-full-access"
    required: false
    default: "workspace-write"
  codex_safety_strategy:
    description: "Safety strategy for Codex: drop-sudo, unprivileged-user, read-only, or unsafe"
    required: false
    default: "drop-sudo"
  # Common inputs
  branch_prefix:
    description: "Prefix for generated branches"
    required: false
    default: "ai/"
  pr_title_template:
    description: "Template for created PR title (supports variable placeholders)"
    required: false
    default: "chore: Automated changes from PR #{{PR_NUMBER}}"
  pr_body_template:
    description: "Template for created PR body (supports variable placeholders)"
    required: false
    default: "This PR contains automated changes generated by AI based on merged PR #{{PR_NUMBER}}."
  base_branch:
    description: "Base branch to create new branch from (defaults to repository default branch)"
    required: false
  github_token:
    description: "GitHub API token (pass secrets.GITHUB_TOKEN from your workflow)"
    required: true
  # Plan phase inputs
  enable_plan:
    description: "Enable plan phase before implementation (runs LLM twice: once for planning, once for implementation)"
    required: false
    default: "false"
  plan_prompt_template:
    description: "Optional prompt template for the plan phase. If not provided, uses a default plan prompt."
    required: false
  plan_claude_args:
    description: "Additional arguments to pass directly to Claude CLI for plan phase (e.g., '--model claude-opus-4-1-20250805 --max-turns 3')"
    required: false
    default: ""
outputs:
  branch_name:
    description: "Name of the branch created by the AI assistant"
    value: ${{ steps.ai-execution.outputs.branch_name }}
  has_changes:
    description: "Whether the AI assistant made any changes"
    value: ${{ steps.ai-execution.outputs.has_changes }}
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun install

    - name: Install Codex CLI
      if: inputs.provider == 'codex' && inputs.enable_plan == 'true'
      shell: bash
      run: npm install -g @openai/codex

    - name: Extract PR number from event
      id: extract-pr-number
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/extract-pr-number.ts
      env:
        PR_NUMBER: ${{ inputs.pr_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
        GITHUB_API_URL: ${{ github.api_url }}

    - name: Set default plan prompt template
      id: set-plan-prompt-default
      if: inputs.enable_plan == 'true'
      shell: bash
      run: |
        PLAN_FILE="${{ runner.temp }}/plan.txt"
        if [ -z "${{ inputs.plan_prompt_template }}" ]; then
          {
            echo 'plan_prompt_template<<EOF'
            echo 'Create a detailed plan for implementing the changes described in PR #{{PR_NUMBER}}: {{PR_TITLE}}'
            echo ''
            echo 'PR Description:'
            echo '{{PR_BODY}}'
            echo ''
            echo 'Changed Files:'
            echo '{{CHANGED_FILES}}'
            echo ''
            echo 'Analyze the requirements and break down the work into clear, actionable steps. Consider the code changes needed, potential edge cases, and testing requirements.'
            echo ''
            echo "IMPORTANT: Write your plan to the file $PLAN_FILE (or use the RUNNER_TEMP environment variable: \$RUNNER_TEMP/plan.txt). Do not make any other changes to the codebase - only write the plan file."
            echo 'EOF'
          } >> $GITHUB_OUTPUT
        else
          {
            echo 'plan_prompt_template<<EOF'
            echo "${{ inputs.plan_prompt_template }}"
            echo ''
            echo "IMPORTANT: Write your plan to the file $PLAN_FILE (or use the RUNNER_TEMP environment variable: \$RUNNER_TEMP/plan.txt). Do not make any other changes to the codebase - only write the plan file."
            echo 'EOF'
          } >> $GITHUB_OUTPUT
        fi
        echo "plan_file=$PLAN_FILE" >> $GITHUB_OUTPUT

    - name: Prepare plan prompt with PR data
      id: prepare-plan-prompt
      if: inputs.enable_plan == 'true'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/prepare-prompt.ts
      env:
        PROMPT_TEMPLATE: ${{ steps.set-plan-prompt-default.outputs.plan_prompt_template }}
        PR_NUMBER: ${{ steps.extract-pr-number.outputs.pr_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPOSITORY: ${{ github.repository }}
        BASE_BRANCH: ${{ inputs.base_branch || '' }}

    - name: Run plan phase (Claude)
      id: plan-phase-claude
      if: inputs.enable_plan == 'true' && inputs.provider == 'claude'
      uses: anthropics/claude-code-action@v1
      with:
        prompt: ${{ steps.prepare-plan-prompt.outputs.final_prompt }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        use_bedrock: ${{ inputs.use_bedrock }}
        use_vertex: ${{ inputs.use_vertex }}
        use_foundry: ${{ inputs.use_foundry }}
        claude_args: ${{ inputs.plan_claude_args || inputs.claude_args }}
        settings: ${{ inputs.settings }}
        use_node_cache: ${{ inputs.use_node_cache }}
        path_to_claude_code_executable: ${{ inputs.path_to_claude_code_executable }}
        path_to_bun_executable: ${{ inputs.path_to_bun_executable }}
        show_full_output: ${{ inputs.show_full_output }}
        plugins: ${{ inputs.plugins }}
        plugin_marketplaces: ${{ inputs.plugin_marketplaces }}

    - name: Run plan phase (Codex)
      id: plan-phase-codex
      if: inputs.enable_plan == 'true' && inputs.provider == 'codex'
      uses: openai/codex-action@v1
      with:
        openai-api-key: ${{ inputs.openai_api_key }}
        responses-api-endpoint: ${{ inputs.responses_api_endpoint }}
        prompt: ${{ steps.prepare-plan-prompt.outputs.final_prompt }}
        sandbox: read-only
        safety-strategy: read-only
        codex-args: ${{ inputs.codex_args }}
        output-file: ${{ steps.set-plan-prompt-default.outputs.plan_file }}

    - name: Extract plan from file (Claude)
      id: extract-plan-claude
      if: inputs.enable_plan == 'true' && inputs.provider == 'claude'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        PLAN=$(bun run scripts/extract-plan-from-file.ts)
        echo "plan<<EOF" >> $GITHUB_OUTPUT
        echo "$PLAN" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      env:
        PLAN_FILE: ${{ steps.set-plan-prompt-default.outputs.plan_file }}

    - name: Extract plan from file (Codex)
      id: extract-plan-codex
      if: inputs.enable_plan == 'true' && inputs.provider == 'codex'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        PLAN=$(bun run scripts/extract-plan-from-file.ts)
        echo "plan<<EOF" >> $GITHUB_OUTPUT
        echo "$PLAN" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      env:
        PLAN_FILE: ${{ steps.set-plan-prompt-default.outputs.plan_file }}

    - name: Prepare prompt with PR data
      id: prepare-prompt
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/prepare-prompt.ts
      env:
        PROMPT_TEMPLATE: ${{ inputs.prompt_template }}
        PR_NUMBER: ${{ steps.extract-pr-number.outputs.pr_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPOSITORY: ${{ github.repository }}
        BASE_BRANCH: ${{ inputs.base_branch || '' }}
        PLAN: ${{ steps.extract-plan-claude.outputs.plan || steps.extract-plan-codex.outputs.plan || steps.plan-phase-codex.outputs.final-message || '' }}

    # Create branch for AI execution
    - name: Create branch
      id: create-branch
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/create-branch.ts
      env:
        BASE_BRANCH: ${{ steps.prepare-prompt.outputs.base_branch }}
        BRANCH_PREFIX: ${{ inputs.branch_prefix }}
        PR_NUMBER: ${{ steps.prepare-prompt.outputs.pr_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}

    # Claude Code execution using sanctioned action
    - name: Run Claude Code
      id: claude-code
      if: inputs.provider == 'claude'
      uses: anthropics/claude-code-action@v1
      with:
        prompt: ${{ steps.prepare-prompt.outputs.final_prompt }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        use_bedrock: ${{ inputs.use_bedrock }}
        use_vertex: ${{ inputs.use_vertex }}
        use_foundry: ${{ inputs.use_foundry }}
        claude_args: ${{ inputs.claude_args }}
        settings: ${{ inputs.settings }}
        use_node_cache: ${{ inputs.use_node_cache }}
        path_to_claude_code_executable: ${{ inputs.path_to_claude_code_executable }}
        path_to_bun_executable: ${{ inputs.path_to_bun_executable }}
        show_full_output: ${{ inputs.show_full_output }}
        plugins: ${{ inputs.plugins }}
        plugin_marketplaces: ${{ inputs.plugin_marketplaces }}

    - name: Commit and push changes
      id: commit-push-claude
      if: inputs.provider == 'claude'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/commit-and-push.ts
      env:
        BRANCH_NAME: ${{ steps.create-branch.outputs.branch_name }}
        PR_NUMBER: ${{ steps.prepare-prompt.outputs.pr_number }}
        PROVIDER: "claude"

    # Codex execution
    - name: Run Codex
      id: codex-exec
      if: inputs.provider == 'codex'
      uses: openai/codex-action@v1
      with:
        openai-api-key: ${{ inputs.openai_api_key }}
        responses-api-endpoint: ${{ inputs.responses_api_endpoint }}
        prompt: ${{ steps.prepare-prompt.outputs.final_prompt }}
        sandbox: ${{ inputs.codex_sandbox }}
        safety-strategy: ${{ inputs.codex_safety_strategy }}
        codex-args: ${{ inputs.codex_args }}

    - name: Commit and push changes
      id: commit-push-codex
      if: inputs.provider == 'codex'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/commit-and-push.ts
      env:
        BRANCH_NAME: ${{ steps.create-branch.outputs.branch_name }}
        PR_NUMBER: ${{ steps.prepare-prompt.outputs.pr_number }}
        PROVIDER: "codex"

    # Set unified outputs
    - name: Set AI execution outputs
      id: ai-execution
      shell: bash
      run: |
        # Check Claude outputs if provider is claude
        if [ "${{ inputs.provider }}" == "claude" ] && [ "${{ steps.commit-push-claude.outputs.has_changes }}" == "true" ]; then
          echo "branch_name=${{ steps.commit-push-claude.outputs.branch_name }}" >> $GITHUB_OUTPUT
          echo "has_changes=true" >> $GITHUB_OUTPUT
        # Check Codex outputs if provider is codex
        elif [ "${{ inputs.provider }}" == "codex" ] && [ "${{ steps.commit-push-codex.outputs.has_changes }}" == "true" ]; then
          echo "branch_name=${{ steps.commit-push-codex.outputs.branch_name }}" >> $GITHUB_OUTPUT
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Create PR if changes exist
      if: steps.ai-execution.outputs.has_changes == 'true'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: bun run scripts/create-pr.ts
      env:
        BRANCH_NAME: ${{ steps.ai-execution.outputs.branch_name }}
        BASE_BRANCH: ${{ steps.prepare-prompt.outputs.base_branch }}
        PR_TITLE_TEMPLATE: ${{ inputs.pr_title_template }}
        PR_BODY_TEMPLATE: ${{ inputs.pr_body_template }}
        PR_NUMBER: ${{ steps.prepare-prompt.outputs.pr_number }}
        PR_TITLE: ${{ steps.prepare-prompt.outputs.pr_title }}
        PR_AUTHOR: ${{ steps.prepare-prompt.outputs.pr_author }}
        PR_BODY: ${{ steps.prepare-prompt.outputs.pr_body }}
        REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
